# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
    front_steer_joint:
        p: 20.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true        
